services:
  postgreSQL:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pbl-network

  app:
    image: imjuyongp/pbl:latest # 추후에 도커 허브에 저장할 이미지 계정이랑 이미지 이름 설정하기
    ports:
      - "8080:8080"  # 호스트의 8080 포트를 컨테이너의 8080 포트와 매핑
    env_file:
      - .env # 팀원들끼리만 공유
    environment:
      - SPRING_PROFILES_ACTIVE=prod # 서브모듈 환경변수 prod 버전 인식
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar app.jar
      # 실행 명령어: jar 파일을 실행하면서 Spring 프로필 활성화
    depends_on:
      - postgreSQL  # 이 서비스가 mysql이 먼저 실행된 후 시작되도록
    networks:
      - pbl-network  # services 끼리는 같은 네트워크를 공유

networks:
  pbl-network:
    driver: bridge  # Docker 기본 브리지 네트워크를 사용

volumes:
  postgres-data: